name: Docker CI Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Build Docker image2
      run: docker build -f Dockerfile.dev -t my-pyhton-app .

    - name: Run Docker container
      run: docker run my-python-app
